### PR TITLE
Added support for pagy

### PR DESCRIPTION
**Pull request by iainbeeston**
Pagy is another pagination gem:

https://github.com/ddnexus/pagy

I've added support for it alongside will_paginate and kaminari, using
those as a guide.

The main difference between pagy and the other two is that it doesn't
add scope methods to ActiveRecord::Base but instead paginates using a
controller helper method.

### CODE REVIEW

**Comment by iainbeeston** [comment]
Sorry @jgraichen - the build on this PR was failing for a while, but I think it's good to review now

**Comment by jgraichen** [comment]
No Problem! Thanks for your contribution @iainbeeston. I've invited you as a collaborator. Please feel free to hack on the code as much as you like.

**Comment by jgraichen** [comment]
Your code looks very good. Would you like to have a new release soon?

**Comment by iainbeeston** [comment]
Thanks! By the way, I forgot to add an entry to the CHANGELOG. I don't need a new release urgently, feel free to release any time you're ready

**Comment by franzliedke** [comment]
This has just been released as v1.8.0. Thanks for the contribution!

**Pull request merged**
