### PR TITLE
Add support for HEAD request

### PR DESCRIPTION
**Pull request by Looooong**
Sometimes, we would like to count without getting the whole collection.

### CODE REVIEW

**Comment by franzliedke** [comment]
Makes sense, IMO.

@Looooong Could you add a test case to`paginate_responder_spec.rb`, please?

**Comment by Looooong** [comment]
Alright, what should I test for? Links and headers?

**Comment by franzliedke** [comment]
IMO, yes. Edge cases are already tested for GET requests. So, it should be enough if you do only one `describe` block for the HEAD request, which essentially mirrors [these](https://github.com/jgraichen/paginate-responder/blob/b41086e26d4e7ce11ea2ea92dc81d13e5cba2c63/spec/paginate_responder_spec.rb#L89-L92) and [these](https://github.com/jgraichen/paginate-responder/blob/b41086e26d4e7ce11ea2ea92dc81d13e5cba2c63/spec/paginate_responder_spec.rb#L155-L158) test cases.

**Comment by Looooong** [comment]
@franzliedke I have added tests as requested.

**Comment by franzliedke** [comment]
Beautiful, thanks!

**Comment by franzliedke** [comment]
Released this as v2.1.0.

Please note the [potentially breaking changes](https://github.com/jgraichen/paginate-responder/blob/master/CHANGELOG.md#200---2019-02-19) in v2.0 - but I assume you know about them, as the code was rebased on the latest master. 👍

**Pull request merged**
