### PR TITLE
Add support for HEAD request

### PR DESCRIPTION
**Pull request by Looooong**

### CODE REVIEW

**Comment by jgraichen** [comment]
Awesome! Thanks for contributing.

Can you rebase your changes on the current HEAD so that I can merge and release a new version?

**Comment by Looooong** [comment]
@jgraichen I modified this code 5 years ago. After a quick look through my repos, I saw this and thought I can contribute a PR. Unfortunately, I don't have the same environment setup as 5 years ago so I cannot run the test. Can you rebase and run the test for me instead?

**Comment by jgraichen** [comment]
Ah, thanks for that.

If it's not urgent, I can take a look later. I'd assume the conflict in the specs only, where testing for Rails < 6 was dropped.

**Comment by jgraichen** [comment]
I had issues resolving the conflict because you already contributed that in https://github.com/jgraichen/paginate-responder/pull/12 six years ago. :joy: 

Thanks again!

**Comment by Looooong** [comment]
Lol, I didn't realize 😅

**Pull request closed without merging**
